# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Social Dynamics Lab
tagline:          social science blog
url:              http://socdyn.github.io
paginate:         1
baseurl:          /
author:
  name:           SDL
  url:            http://socdyn.github.io
  email:          

pages_list:     
  About: '/about'
  Archive: '/archive'
  #Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/socdyn/socdyn.github.io
